//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestingPlatformEntities : DbContext
    {
        public TestingPlatformEntities()
            : base("name=TestingPlatformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserSkils> UserSkils { get; set; }
    }
}
